- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/ocean_current"
  gz_topic_name: "/model/bluerov2/ocean_current"
  ros_type_name: "geometry_msgs/msg/Vector3"
  gz_type_name: "gz.msgs.Vector3d"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS    # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/joint_states"
  gz_topic_name: "/world/ocean/model/bluerov2/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS    # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/tf"
  gz_topic_name: "/model/bluerov2/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/bluerov2/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz
# Note: QoS override for /tf_static is set in the launch file:
# Parameter: qos_overrides./tf_static.publisher.durability
# Value: transient_local

- ros_topic_name: "/bluerov2/odometry"
  gz_topic_name: "/model/bluerov2/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/imu"
  gz_topic_name: "/model/bluerov2/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/dvl/velocity_notStamped"
  gz_topic_name: "/model/bluerov2/dvl_ros_compatible/velocity"
  ros_type_name: "geometry_msgs/msg/TwistWithCovariance"
  gz_type_name: "gz.msgs.TwistWithCovariance"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/dvl/range"
  gz_topic_name: "/model/bluerov2/dvl_ros_compatible/range"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/camera_info"
  gz_topic_name: "/model/bluerov2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/camera/image"
  gz_topic_name: "/model/bluerov2/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/depth_camera/image"
  gz_topic_name: "/model/bluerov2/depth_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/depth_camera/points"
  gz_topic_name: "/model/bluerov2/depth_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/thruster1/cmd_thrust"
  gz_topic_name: "/model/bluerov2/joint/thruster1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: ROS_TO_GZ      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/thruster2/cmd_thrust"
  gz_topic_name: "/model/bluerov2/joint/thruster2_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: ROS_TO_GZ      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/thruster3/cmd_thrust"
  gz_topic_name: "/model/bluerov2/joint/thruster3_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: ROS_TO_GZ      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/thruster4/cmd_thrust"
  gz_topic_name: "/model/bluerov2/joint/thruster4_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: ROS_TO_GZ      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/thruster5/cmd_thrust"
  gz_topic_name: "/model/bluerov2/joint/thruster5_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: ROS_TO_GZ      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

- ros_topic_name: "/bluerov2/thruster6/cmd_thrust"
  gz_topic_name: "/model/bluerov2/joint/thruster6_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true                # Default "false"
  direction: ROS_TO_GZ      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz